export interface MidEntry {
  mid: number
  iso: string
  country: string
}

export const MID_TABLE: MidEntry[] = [
  { mid: 201, iso: 'AL', country: 'Albania' },
  { mid: 202, iso: 'AT', country: 'Austria' },
  { mid: 203, iso: 'BE', country: 'Belgium' },
  { mid: 204, iso: 'BY', country: 'Belarus' },
  { mid: 205, iso: 'BG', country: 'Bulgaria' },
  { mid: 206, iso: 'VA', country: 'Vatican' },
  { mid: 207, iso: 'CY', country: 'Cyprus' },
  { mid: 208, iso: 'CZ', country: 'Czech Republic' },
  { mid: 209, iso: 'DK', country: 'Denmark' },
  { mid: 210, iso: 'EE', country: 'Estonia' },
  { mid: 211, iso: 'FI', country: 'Finland' },
  { mid: 212, iso: 'FR', country: 'France' },
  { mid: 213, iso: 'DE', country: 'Germany' },
  { mid: 214, iso: 'GI', country: 'Gibraltar' },
  { mid: 215, iso: 'GR', country: 'Greece' },
  { mid: 216, iso: 'HU', country: 'Hungary' },
  { mid: 218, iso: 'IS', country: 'Iceland' },
  { mid: 219, iso: 'IE', country: 'Ireland' },
  { mid: 220, iso: 'IT', country: 'Italy' },
  { mid: 224, iso: 'LV', country: 'Latvia' },
  { mid: 225, iso: 'LI', country: 'Liechtenstein' },
  { mid: 226, iso: 'LT', country: 'Lithuania' },
  { mid: 227, iso: 'LU', country: 'Luxembourg' },
  { mid: 228, iso: 'MT', country: 'Malta' },
  { mid: 230, iso: 'MD', country: 'Moldova' },
  { mid: 231, iso: 'MC', country: 'Monaco' },
  { mid: 232, iso: 'NL', country: 'Netherlands' },
  { mid: 233, iso: 'NO', country: 'Norway' },
  { mid: 234, iso: 'PL', country: 'Poland' },
  { mid: 235, iso: 'PT', country: 'Portugal' },
  { mid: 236, iso: 'RO', country: 'Romania' },
  { mid: 237, iso: 'SM', country: 'San Marino' },
  { mid: 238, iso: 'SK', country: 'Slovakia' },
  { mid: 239, iso: 'SI', country: 'Slovenia' },
  { mid: 240, iso: 'ES', country: 'Spain' },
  { mid: 241, iso: 'SE', country: 'Sweden' },
  { mid: 242, iso: 'CH', country: 'Switzerland' },
  { mid: 243, iso: 'TR', country: 'Turkey' },
  { mid: 244, iso: 'UA', country: 'Ukraine' },
  { mid: 245, iso: 'GB', country: 'United Kingdom' },
  { mid: 246, iso: 'YU', country: 'Yugoslavia' },
  { mid: 247, iso: 'HR', country: 'Croatia' },
  { mid: 248, iso: 'SI', country: 'Slovenia' },
  { mid: 249, iso: 'MK', country: 'Macedonia' },
  { mid: 250, iso: 'IE', country: 'Ireland' },
  { mid: 251, iso: 'IS', country: 'Iceland' },
  { mid: 252, iso: 'LI', country: 'Liechtenstein' },
  { mid: 253, iso: 'LU', country: 'Luxembourg' },
  { mid: 254, iso: 'MT', country: 'Malta' },
  { mid: 255, iso: 'MC', country: 'Monaco' },
  { mid: 256, iso: 'NL', country: 'Netherlands' },
  { mid: 257, iso: 'NO', country: 'Norway' },
  { mid: 258, iso: 'PL', country: 'Poland' },
  { mid: 259, iso: 'PT', country: 'Portugal' },
  { mid: 261, iso: 'SK', country: 'Slovakia' },
  { mid: 262, iso: 'SI', country: 'Slovenia' },
  { mid: 263, iso: 'ES', country: 'Spain' },
  { mid: 264, iso: 'SE', country: 'Sweden' },
  { mid: 265, iso: 'CH', country: 'Switzerland' },
  { mid: 266, iso: 'TR', country: 'Turkey' },
  { mid: 267, iso: 'UA', country: 'Ukraine' },
  { mid: 268, iso: 'GB', country: 'United Kingdom' },
  { mid: 269, iso: 'HR', country: 'Croatia' },
  { mid: 270, iso: 'RU', country: 'Russia' },
  { mid: 271, iso: 'RU', country: 'Russia' },
  { mid: 272, iso: 'RU', country: 'Russia' },
  { mid: 273, iso: 'RU', country: 'Russia' },
  { mid: 274, iso: 'RU', country: 'Russia' },
  { mid: 275, iso: 'RU', country: 'Russia' },
  { mid: 276, iso: 'RU', country: 'Russia' },
  { mid: 277, iso: 'RU', country: 'Russia' },
  { mid: 278, iso: 'RU', country: 'Russia' },
  { mid: 279, iso: 'RU', country: 'Russia' },
  { mid: 301, iso: 'AI', country: 'Anguilla' },
  { mid: 303, iso: 'US', country: 'Alaska USA' },
  { mid: 304, iso: 'AG', country: 'Antigua Barbuda' },
  { mid: 305, iso: 'AG', country: 'Antigua Barbuda' },
  { mid: 306, iso: 'AW', country: 'Aruba' },
  { mid: 307, iso: 'BS', country: 'Bahamas' },
  { mid: 308, iso: 'BS', country: 'Bahamas' },
  { mid: 309, iso: 'BS', country: 'Bahamas' },
  { mid: 310, iso: 'BM', country: 'Bermuda' },
  { mid: 311, iso: 'BS', country: 'Bahamas' },
  { mid: 312, iso: 'BZ', country: 'Belize' },
  { mid: 314, iso: 'BB', country: 'Barbados' },
  { mid: 316, iso: 'CA', country: 'Canada' },
  { mid: 319, iso: 'KY', country: 'Cayman Islands' },
  { mid: 321, iso: 'CR', country: 'Costa Rica' },
  { mid: 323, iso: 'CU', country: 'Cuba' },
  { mid: 325, iso: 'DM', country: 'Dominica' },
  { mid: 327, iso: 'DO', country: 'Dominican Republic' },
  { mid: 329, iso: 'SV', country: 'El Salvador' },
  { mid: 330, iso: 'GD', country: 'Grenada' },
  { mid: 331, iso: 'GL', country: 'Greenland' },
  { mid: 332, iso: 'GT', country: 'Guatemala' },
  { mid: 334, iso: 'HT', country: 'Haiti' },
  { mid: 336, iso: 'HN', country: 'Honduras' },
  { mid: 338, iso: 'JM', country: 'Jamaica' },
  { mid: 339, iso: 'KN', country: 'Saint Kitts Nevis' },
  { mid: 341, iso: 'LC', country: 'Saint Lucia' },
  { mid: 343, iso: 'MX', country: 'Mexico' },
  { mid: 345, iso: 'PM', country: 'St Pierre Miquelon' },
  { mid: 347, iso: 'VC', country: 'Saint Vincent' },
  { mid: 348, iso: 'TT', country: 'Trinidad Tobago' },
  { mid: 350, iso: 'TC', country: 'Turks Caicos' },
  { mid: 351, iso: 'US', country: 'USA' },
  { mid: 352, iso: 'US', country: 'USA' },
  { mid: 353, iso: 'US', country: 'USA' },
  { mid: 354, iso: 'US', country: 'USA' },
  { mid: 355, iso: 'US', country: 'USA' },
  { mid: 356, iso: 'US', country: 'USA' },
  { mid: 357, iso: 'US', country: 'USA' },
  { mid: 358, iso: 'US', country: 'USA' },
  { mid: 359, iso: 'US', country: 'USA' },
  { mid: 361, iso: 'US', country: 'USA' },
  { mid: 362, iso: 'US', country: 'USA' },
  { mid: 363, iso: 'US', country: 'USA' },
  { mid: 364, iso: 'US', country: 'USA' },
  { mid: 365, iso: 'US', country: 'USA' },
  { mid: 366, iso: 'US', country: 'USA' },
  { mid: 367, iso: 'US', country: 'USA' },
  { mid: 368, iso: 'US', country: 'USA' },
  { mid: 369, iso: 'US', country: 'USA' },
  { mid: 370, iso: 'PA', country: 'Panama' },
  { mid: 371, iso: 'PA', country: 'Panama' },
  { mid: 372, iso: 'PA', country: 'Panama' },
  { mid: 373, iso: 'PA', country: 'Panama' },
  { mid: 374, iso: 'PA', country: 'Panama' },
  { mid: 375, iso: 'PA', country: 'Panama' },
  { mid: 376, iso: 'PA', country: 'Panama' },
  { mid: 377, iso: 'PA', country: 'Panama' },
  { mid: 378, iso: 'PA', country: 'Panama' },
  { mid: 379, iso: 'PA', country: 'Panama' },
  { mid: 401, iso: 'AF', country: 'Afghanistan' },
  { mid: 403, iso: 'SA', country: 'Saudi Arabia' },
  { mid: 405, iso: 'BD', country: 'Bangladesh' },
  { mid: 408, iso: 'BH', country: 'Bahrain' },
  { mid: 410, iso: 'BT', country: 'Bhutan' },
  { mid: 412, iso: 'CN', country: 'China' },
  { mid: 413, iso: 'CN', country: 'China' },
  { mid: 414, iso: 'CN', country: 'China' },
  { mid: 416, iso: 'TW', country: 'Taiwan' },
  { mid: 417, iso: 'KH', country: 'Cambodia' },
  { mid: 419, iso: 'CY', country: 'Cyprus' },
  { mid: 422, iso: 'IN', country: 'India' },
  { mid: 423, iso: 'ID', country: 'Indonesia' },
  { mid: 425, iso: 'IR', country: 'Iran' },
  { mid: 428, iso: 'IQ', country: 'Iraq' },
  { mid: 431, iso: 'IL', country: 'Israel' },
  { mid: 432, iso: 'JP', country: 'Japan' },
  { mid: 433, iso: 'JP', country: 'Japan' },
  { mid: 434, iso: 'JP', country: 'Japan' },
  { mid: 435, iso: 'JP', country: 'Japan' },
  { mid: 436, iso: 'JP', country: 'Japan' },
  { mid: 437, iso: 'JO', country: 'Jordan' },
  { mid: 438, iso: 'KZ', country: 'Kazakhstan' },
  { mid: 440, iso: 'KR', country: 'South Korea' },
  { mid: 441, iso: 'KR', country: 'South Korea' },
  { mid: 443, iso: 'KP', country: 'North Korea' },
  { mid: 445, iso: 'KW', country: 'Kuwait' },
  { mid: 447, iso: 'LB', country: 'Lebanon' },
  { mid: 450, iso: 'MO', country: 'Macau' },
  { mid: 451, iso: 'MY', country: 'Malaysia' },
  { mid: 453, iso: 'MV', country: 'Maldives' },
  { mid: 455, iso: 'MN', country: 'Mongolia' },
  { mid: 457, iso: 'MM', country: 'Myanmar' },
  { mid: 459, iso: 'NP', country: 'Nepal' },
  { mid: 461, iso: 'OM', country: 'Oman' },
  { mid: 463, iso: 'PK', country: 'Pakistan' },
  { mid: 466, iso: 'PH', country: 'Philippines' },
  { mid: 468, iso: 'QA', country: 'Qatar' },
  { mid: 470, iso: 'LK', country: 'Sri Lanka' },
  { mid: 472, iso: 'SY', country: 'Syria' },
  { mid: 473, iso: 'TJ', country: 'Tajikistan' },
  { mid: 475, iso: 'TH', country: 'Thailand' },
  { mid: 477, iso: 'AE', country: 'UAE' },
  { mid: 478, iso: 'UZ', country: 'Uzbekistan' },
  { mid: 479, iso: 'VN', country: 'Vietnam' },
  { mid: 480, iso: 'VN', country: 'Vietnam' },
  { mid: 481, iso: 'VN', country: 'Vietnam' },
  { mid: 482, iso: 'VN', country: 'Vietnam' },
  { mid: 483, iso: 'VN', country: 'Vietnam' },
  { mid: 484, iso: 'VN', country: 'Vietnam' },
  { mid: 485, iso: 'YE', country: 'Yemen' },
  { mid: 501, iso: 'AO', country: 'Angola' },
  { mid: 503, iso: 'DZ', country: 'Algeria' },
  { mid: 505, iso: 'BJ', country: 'Benin' },
  { mid: 506, iso: 'BW', country: 'Botswana' },
  { mid: 507, iso: 'BF', country: 'Burkina Faso' },
  { mid: 508, iso: 'BI', country: 'Burundi' },
  { mid: 509, iso: 'CM', country: 'Cameroon' },
  { mid: 510, iso: 'CV', country: 'Cape Verde' },
  { mid: 511, iso: 'CF', country: 'Central African Republic' },
  { mid: 512, iso: 'TD', country: 'Chad' },
  { mid: 513, iso: 'KM', country: 'Comoros' },
  { mid: 514, iso: 'CG', country: 'Congo' },
  { mid: 515, iso: 'CD', country: 'DR Congo' },
  { mid: 516, iso: 'CI', country: 'Ivory Coast' },
  { mid: 517, iso: 'DJ', country: 'Djibouti' },
  { mid: 518, iso: 'EG', country: 'Egypt' },
  { mid: 519, iso: 'GQ', country: 'Equatorial Guinea' },
  { mid: 520, iso: 'ER', country: 'Eritrea' },
  { mid: 521, iso: 'ET', country: 'Ethiopia' },
  { mid: 522, iso: 'GA', country: 'Gabon' },
  { mid: 523, iso: 'GM', country: 'Gambia' },
  { mid: 524, iso: 'GH', country: 'Ghana' },
  { mid: 525, iso: 'GN', country: 'Guinea' },
  { mid: 526, iso: 'GW', country: 'Guinea Bissau' },
  { mid: 527, iso: 'KE', country: 'Kenya' },
  { mid: 528, iso: 'LS', country: 'Lesotho' },
  { mid: 529, iso: 'LR', country: 'Liberia' },
  { mid: 530, iso: 'LY', country: 'Libya' },
  { mid: 531, iso: 'MG', country: 'Madagascar' },
  { mid: 532, iso: 'MW', country: 'Malawi' },
  { mid: 533, iso: 'ML', country: 'Mali' },
  { mid: 534, iso: 'MR', country: 'Mauritania' },
  { mid: 535, iso: 'MU', country: 'Mauritius' },
  { mid: 536, iso: 'MA', country: 'Morocco' },
  { mid: 537, iso: 'MZ', country: 'Mozambique' },
  { mid: 538, iso: 'NA', country: 'Namibia' },
  { mid: 539, iso: 'NE', country: 'Niger' },
  { mid: 540, iso: 'NG', country: 'Nigeria' },
  { mid: 541, iso: 'RW', country: 'Rwanda' },
  { mid: 542, iso: 'ST', country: 'Sao Tome Principe' },
  { mid: 544, iso: 'SN', country: 'Senegal' },
  { mid: 545, iso: 'SC', country: 'Seychelles' },
  { mid: 546, iso: 'SL', country: 'Sierra Leone' },
  { mid: 547, iso: 'SO', country: 'Somalia' },
  { mid: 548, iso: 'ZA', country: 'South Africa' },
  { mid: 549, iso: 'SD', country: 'Sudan' },
  { mid: 550, iso: 'SR', country: 'Suriname' },
  { mid: 551, iso: 'SZ', country: 'Eswatini' },
  { mid: 552, iso: 'TZ', country: 'Tanzania' },
  { mid: 553, iso: 'TG', country: 'Togo' },
  { mid: 554, iso: 'TN', country: 'Tunisia' },
  { mid: 555, iso: 'UG', country: 'Uganda' },
  { mid: 556, iso: 'CD', country: 'DR Congo' },
  { mid: 557, iso: 'ZM', country: 'Zambia' },
  { mid: 558, iso: 'ZW', country: 'Zimbabwe' },
  { mid: 601, iso: 'AU', country: 'Australia' },
  { mid: 603, iso: 'AU', country: 'Australia' },
  { mid: 604, iso: 'AU', country: 'Australia' },
  { mid: 605, iso: 'AU', country: 'Australia' },
  { mid: 606, iso: 'AU', country: 'Australia' },
  { mid: 607, iso: 'AU', country: 'Australia' },
  { mid: 611, iso: 'CK', country: 'Cook Islands' },
  { mid: 612, iso: 'FJ', country: 'Fiji' },
  { mid: 613, iso: 'PF', country: 'French Polynesia' },
  { mid: 614, iso: 'KI', country: 'Kiribati' },
  { mid: 616, iso: 'MH', country: 'Marshall Islands' },
  { mid: 617, iso: 'FM', country: 'Micronesia' },
  { mid: 618, iso: 'NR', country: 'Nauru' },
  { mid: 619, iso: 'NC', country: 'New Caledonia' },
  { mid: 620, iso: 'NZ', country: 'New Zealand' },
  { mid: 621, iso: 'NU', country: 'Niue' },
  { mid: 622, iso: 'PG', country: 'Papua New Guinea' },
  { mid: 623, iso: 'PW', country: 'Palau' },
  { mid: 625, iso: 'WS', country: 'Samoa' },
  { mid: 626, iso: 'SB', country: 'Solomon Islands' },
  { mid: 627, iso: 'TO', country: 'Tonga' },
  { mid: 628, iso: 'TV', country: 'Tuvalu' },
  { mid: 629, iso: 'VU', country: 'Vanuatu' },
  { mid: 701, iso: 'AR', country: 'Argentina' },
  { mid: 710, iso: 'BR', country: 'Brazil' },
  { mid: 720, iso: 'BO', country: 'Bolivia' },
  { mid: 725, iso: 'CL', country: 'Chile' },
  { mid: 730, iso: 'CO', country: 'Colombia' },
  { mid: 735, iso: 'EC', country: 'Ecuador' },
  { mid: 740, iso: 'FK', country: 'Falkland Islands' },
  { mid: 745, iso: 'GF', country: 'French Guiana' },
  { mid: 750, iso: 'GY', country: 'Guyana' },
  { mid: 755, iso: 'PY', country: 'Paraguay' },
  { mid: 760, iso: 'PE', country: 'Peru' },
  { mid: 765, iso: 'SR', country: 'Suriname' },
  { mid: 770, iso: 'UY', country: 'Uruguay' },
  { mid: 775, iso: 'VE', country: 'Venezuela' },
]

const MID_MAP = new Map<number, MidEntry>(MID_TABLE.map((e) => [e.mid, e]))

export function flagFromMmsi(mmsi: number): MidEntry | null {
  if (!mmsi || mmsi < 100000000 || mmsi > 999999999) return null
  const mid = Math.floor(mmsi / 1000000)
  return MID_MAP.get(mid) ?? null
}

const ISO_TO_EMOJI_OFFSET = 0x1f1e6

export function isoToFlagEmoji(iso: string): string {
  if (!iso || iso.length !== 2) return ''
  const code = iso.toUpperCase()
  const a = ISO_TO_EMOJI_OFFSET + (code.charCodeAt(0) - 65)
  const b = ISO_TO_EMOJI_OFFSET + (code.charCodeAt(1) - 65)
  return String.fromCodePoint(a, b)
}
